# Run with:
# ansible-playbook InitDockerSwarm.yml

---
- name: Initialize docker swarm
  hosts: swarmhosts
  tasks:
  - name: Check if Swarm has already been Initialized
    shell: docker node ls
    register: swarm_status
    ignore_errors: true
    tags: swarm

  - name: Initialize Docker Swarm
    docker_swarm:
      state: present
      advertise_addr: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}" 
    when: swarm_status.rc != 0
    run_once: true
    tags: swarm

  - name: Get the Manager join-token
    shell: docker swarm join-token --quiet manager
    register: manager_token
    tags: swarm

  - name: Get the worker join-token
    shell: docker swarm join-token --quiet worker
    register: worker_token
    tags: swarm

- name: Add Workers to the Swarm
  hosts: swarmclients
  tasks:

  - name: Join the worker to the swarm
    docker_swarm:
      state: join
      advertise_addr: "{{ ansible_host }}"
      join_token: "{{ hostvars['192.168.0.60']['worker_token']['stdout'] }}"
      remote_addrs: [ "{{ hostvars['192.168.0.60']['ansible_default_ipv4']['address'] }}:2377" ]
    tags: swarm
